apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-frontend
  namespace: my-app
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: my-frontend
  template:
    metadata:
      labels:
        app: my-frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.repository }}:{{ .Values.frontend.tag }}"
          ports:
            - containerPort: {{ .Values.frontend.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: my-frontend-service
  namespace: my-app
spec:
  selector:
    app: my-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.frontend.port }}