apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-app-ingress
  namespace: my-app
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: app.local
      http:
        paths:
          # Основной фронтенд
          - path: /
            pathType: Prefix
            backend:
              service:
                name: my-frontend-service
                port:
                  number: 80
          # Проксирование запросов к API бэкенда
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: my-backend-service
                port:
                  number: 5000