backend:
  repository: voronyukea/my-backend
  tag: "1f4251b1b7bc3926ad2914587b146dbc68fd3921"
  port: 5000
  replicaCount: 2

frontend:
  repository: voronyukea/my-frontend
  tag: "1f4251b1b7bc3926ad2914587b146dbc68fd3921"
  port: 80
  replicaCount: 2