backend:
  repository: voronyukea/my-backend
  tag: "7ca5a77b373ec8c921f82e780472bcc68705e685"
  port: 5000
  replicaCount: 2

frontend:
  repository: voronyukea/my-frontend
  tag: "7ca5a77b373ec8c921f82e780472bcc68705e685"
  port: 80
  replicaCount: 2