name: Build and Push to Docker Hub

on:
  push:
    branches:
      - main  # Пайплайн будет срабатывать при каждом пуше в ветку main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Скачиваем код репозитория на виртуальную машину GitHub
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Логинимся в Docker Hub, используя наши секреты
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 3: Настраиваем Docker Buildx для эффективной сборки
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 4: Собираем и пушим БЭКЕНД
      - name: Build and Push Backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          # Мы даем два тега: latest (всегда актуальный) и короткий SHA коммита (для Argo CD)
          tags: |
            voronyukea/my-backend:latest
            voronyukea/my-backend:${{ github.sha }}

      # Step 5: Собираем и пушим ФРОНТЕНД
      - name: Build and Push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: |
            voronyukea/my-frontend:latest
            voronyukea/my-frontend:${{ github.sha }}

      # Step 6: Автоматически обновляем тег в values.yaml внутри Helm-чарта
      - name: Update image tags in Helm values
        run: |
          sed -i 's|tag: .*|tag: "${{ github.sha }}"|g' ./k8s-helm/values.yaml
          
      # Step 7: Коммитим измененный values.yaml обратно в репозиторий
      - name: Commit and Push changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add ./k8s-helm/values.yaml
          git commit -m "image tag update to ${{ github.sha }} [skip ci]"
          git push origin main